name: 'Issue - Initial labeling'

on:
  issues:
    types: 
    - opened
    - reopened

jobs:

  label_issues:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: Add labels to indicate user assingee interaction needed
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          # add new label with sperator: ,
          # no whitespaces
          LABELS: time/needed

      - name: Add comment for instructions
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            👋 Hello! Thanks for opening this issue.

            To help us efficiently triage and prioritize this issue, we kindly ask the assignee to estimate the time required to address this issue and add a corresponding tag such as time/XL (Extra Large) or time/S (Small) to indicate its scale. This will assist us in planning and allocating resources effectively.
