name: PR - Verify linked issue

on:
  pull_request:
    types: [opened, reopened]

jobs:
  PR_verify_linked_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.7

      - name: Get Linked Issue
        id: get_issue
        uses: octokit/graphql-action@v2.3.2
        with:
          query: |
            query ($owner: String!, $repo: String!, $pull_number: Int!) {
              repository(owner:$owner, name:$repo) {
                pullRequest(number: $pull_number) {
                  timelineItems(itemTypes: [CONNECTED_EVENT], first: 100) {
                    nodes {
                      ... on ConnectedEvent {
                        subject {
                          ... on Issue {
                            number
                            title
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          variables: |
            {
              "owner": "${{ github.repository_owner }}",
              "repo": "${{ github.event.repository.name }}",
              "pull_number": ${{ github.event.pull_request.number }}
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Linked Issue Data
        run: "echo 'latest release: ${{ steps.get_issue.outputs.data }}'"

      - name: Set output
        id: check_nodes
        run: |
          nodes=$(echo '${{ steps.get_issue.outputs.data }}' | jq '.repository.pullRequest.timelineItems.nodes')
          if [ "$nodes" == "[]" ]; then
            echo "linked_issues=false" >> $GITHUB_ENV
          else
            echo "linked_issues=true" >> $GITHUB_ENV
          fi

      - name: Echo message for No Linked Issue
        run: echo "No linked issue found."
        if: ${{ env.linked_issues == 'false' }}

      - name: Comment for No Linked Issue
        uses: actions/github-script@v7
        if: ${{ env.linked_issues == 'false' }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issueNumber = context.issue.number;
            github.rest.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Your PR has not been linked to an issue. Pull request and issue need to be on the same repository. If you need to transfer an existing issue to this repository, please use [this guide](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository) Please link the corresponding issue in the sidebar or use [keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) in your PR, then close and reopen the PR. For more information, refer to the GitHub principles and conventions defined in [Git & GitHub & GitFlow | Notion](https://www.notion.so/roclub/Git-GitHub-GitFlow-85cbb825be004d4d8b8ff6c0fa12204b)`
            })
      - name: Fail for No Linked Issue
        run: exit 1
        if: ${{ env.linked_issues == 'false' }}
        
      - name: Step for Linked Issue(s)
        run: echo "Linked issue(s) found."
        if: ${{ env.linked_issues == 'true' }}
