# naming of workflow not adapted to avoid duplicates from renamed workflow in synced repositories
name: 'Issue - Add TODO to issue'

on:
  push:
    branches:    
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4
        with:
          AUTO_ASSIGN: true
